### ISSUE TITLE
details of algorithm(s) powering MITIE ?

### ISSUE THREAD

**Issue by anujgupta82** [mit-nlp/MITIE#118]
Is there a paper/write up describing details of MITIE and algorithms that are powering it ?

**Comment by davisking** [comment]
Not really.  Just the comments here on github.  It's basically just dlib's sequence segmenter with the addition of eigenword features, hash features, and some word morphology.

**Comment by anujgupta82** [comment]
So whats is the best way to understand its internals ?

**Comment by davisking** [comment]
I would read the code.  It's not as complicated as you would think since most of it simply uses dlib components which are very well do documented and include citations to the literature.  For instance, this is the fundamental sequence segmentation tool MITIE uses: http://dlib.net/ml.html#structural_sequence_labeling_trainer

**Comment by davisking** [comment]
Also, this is the paper on eigenwords: http://icml.cc/2012/papers/763.pdf
