### ISSUE TITLE
Improving Mitie NER for missing entities

### ISSUE THREAD

**Issue by andessen** [mit-nlp/MITIE#13]
Hello,

So far I'm greatly impressed with the product. The assessment in https://github.com/mit-nlp/MITIE/issues/12 is spot on and I'm looking forward to training some binary relationships as soon as I can think of an interesting one. 

I was wondering if there were plans to update the basic NER model over time. Further, is there some kind of way to submit missed entities within text in an organized fashion? 

This isn't be best example since it's hard to determine from the context but running

    "Popular Science is your wormhole to the future. Reporting on what's new and what's next in science and technology, we deliver the future now."

missed 'Popular Science' as miscellaneous or otherwise without any kind of score.

**Comment by davisking** [comment]
Thanks :)

We don't have any plans to update the models.  The general plan is to add some more features (e.g. document classification, part of speech tagging) rather than to keep tweaking models.  Moreover, an important feature of MITIE is the ability to train custom models.  So if there is some data you have that doesn't work the way you want with the included MITIE model then the idea is that you can train your own custom model.
