### ISSUE TITLE
Support for text classification

### ISSUE THREAD

**Issue by techscientist** [mit-nlp/MITIE#14]
Hi guys,

I am working on a c++ project that requires named entity recognition and text classification.
For the entity recognition, I discovered this MITIE library, which is fast and excellent.
I would also really like to see text classification (c++) built into the project, since entity recognition and text classification can complement each other.

For example, OpenNLP has text classification. Can you guys create a similar text classification, where I have the data in Tab-spaced format.

Example training data:
category             text

If you guys do not have this or not going to implement this, can you please guide me to a C++ library that has good text classification. I am aware of implementations in other languages, but I need to do this in C++.

It would be really great if you machine learning wizards can include a C++ library for text classification!

**Comment by davisking** [comment]
The next thing we add to MITIE is going to be text classification.  It would be in there already but we have been unexpectedly busy with a bunch of other things.  In the meantime, you can easily make text classification tools using one of dlib's linear SVM classification tools (see http://dlib.net/ml.html).  You will have to write the code to convert the text into a feature vector but beyond that dlib has everything else.

**Comment by TechnikEmpire** [comment]
+1 for this, would love to see. Not trying to be one of those github folks that just asks for more. :) Thanks for publishing this lib.

**Comment by davisking** [comment]
Yeah yeah :)

**Comment by jinyichao** [comment]
Hi, Davis. I am now trying to add the text classification (which would be also applied to sentiment analysis) to this repo. And in this process, may I ask you some questions? 
1. Is it applicable to directly use the output of sentence_to_feats(...) function as the feature vector for the text?
2. If the answer is "Yes", then when I try to feed it into the "svm_multiclass_linear_trainer" as "svm_multiclass_linear_trainer<sparse_linear_kernel<std::vector<matrix<float,0,1> > >,unsigned long> trainer", it gives me an error indicating somewhat "the data type is not matched". Is my way to revoke the trainer wrong?
3. If the answer is "No", could you please give me more hints on how to get the text feature vector based on current implementation?

Thanks a lot for your kind and quick reply as always.

**Comment by davisking** [comment]
sentencet_of_feats doesn't produce a feature vector, it produces a set of feature vectors, one for each word.  To do document classification you need create one feature vector (of fixed length) for the entire document.  

Adding document classification to MITIE would require implementing multiple different "document to feature vector" representations from the academic literature.  Then when someone calls train in MITIE it should try all of them, checking the results with cross validation, and then returning the best classifier to the user so that the user doesn't need to think about anything.  So it's a little more complex than you imagine.  A reasonable implementation in MITIE would need to include a few different "bag of words" models as well as some word vector models and likely combinations of the two.

**Comment by jinyichao** [comment]
Thanks very much for your quick and insightful reply! 

In this case, as the first step, is it a right direction to try some simple "document to feature vector" representations, such as getting the summation/average of all word vectors from sentence_to_feats, as the feature vector of the entire document? 

Another question is that, because different "document to feature vector" relies on completely different scheme. While most of them makes use of deep learning network / neural network, which is not included in MITIE, if I am correct. So do you mean that MITIE need to inevitably include deep learning in the near future?

**Comment by davisking** [comment]
You could sum them and that might work fine for some applications.

The most common document to feature vector method is the "bag of words"
method which isn't any kind of neural network.  The other thing that is
popular is the "word vector" method which is sometimes done with a neural
network, but in MITIE we use the eigenword method (
http://www.pdhillon.com/dhillon15a.pdf) which is a better way of estimating
these vectors.  I haven't seen any deep learning methods applied to
document classification, aside from these "word vector" methods already
used by MITIE.

**Comment by jinyichao** [comment]
Yes, I do agree the eigenword based vector representation method is a better way to estimate the word feature vectors. That's also why I am so interested in MITIE. 

Regarding to the neural network based document classifications, there are actually a few attempts. This paper is one of them, https://cs.stanford.edu/~quocle/paragraph_vector.pdf. And basically, it uses almost the same way of word2vec to train the paragraph/document vector together with the word vectors. Although, I am, personally, not a fun of deep learning, it still might be worthy to make some attempts.

Anyway, thank you so much for the extremely valuable explanations! I will start from the simple case by using the simple summation/average method from the code level.

**Comment by davisking** [comment]
Yeah, I know about paragraph vector.  We might add some kind of paragraph
level vector representation to MITIE at some point.  But right now I'm busy
finishing the deep learning tooling in dlib :)

**Comment by jinyichao** [comment]
Yeah, it is always glad to hear about new features are on the way! Thank you for all these great stuffs you shared here! :) :+1:

**Comment by davisking** [comment]
Now addressed by PR https://github.com/mit-nlp/MITIE/pull/49
