### ISSUE TITLE
What text categorizer perform to handle  unknown vocabulary in testing dataset

### ISSUE THREAD

**Issue by shanalikhan** [mit-nlp/MITIE#198]
Hello, 

As text categorizer required the `wordrep` word embeddings.
https://github.com/mit-nlp/MITIE/blob/master/examples/python/text_categorizers_with_shared_feature_extractor.py

I want to know how text categorizer work and perform and know the sentiment of sentence that contains those words that are not available in both training set for embeddings and text categorizer ?

**Comment by davisking** [comment]
It uses eigenword features for words it has seen before.  These are combined with a large set of morphological features designed to map onto the eigenword vectorspace.  So what happens if you get a word it hasn't seen before is it attempts to construct an eigenword vector from only morphology.  This works fine in general.  For instance, it might recognize that a word ending in ing is a verb via this method even if its never seen it before.

**Comment by shanalikhan** [comment]
can you refer to any research paper for it.

**Comment by davisking** [comment]
http://jmlr.csail.mit.edu/papers/volume16/dhillon15a/dhillon15a.pdf

>
