### ISSUE TITLE
Is there any method to make MITIE support Chinese language?

### ISSUE THREAD

**Issue by hiber-niu** [mit-nlp/MITIE#58]
I need to handle Chinese language, so is there any method or some steps that i could try to train NER and binary relation extration model?

Thanks for any help!

**Comment by davisking** [comment]
The example programs show how to train MITIE models.  All you need is annotated data.  You will also need a chinese tokenizer.

**Comment by Tony-HSU** [comment]
@davisking Should I tokenize my Chinese characters before i use `wordrep` to generate `total_word_feature_extractor.dat` ?
For example

1. `今天天氣真好`(original)
1. `今天 天氣 真好`(tokenized)
1. `今 天 天 氣 真 好`(just separate every characters with white space)

which one is prefered?

**Comment by davisking** [comment]
You need to separate it into "words" with spaces between them. I'm not
really sure what the best kind of tokenization is for Chinese though.

**Comment by alejandrokonto** [comment]
@davisking 
To introduce a new language all i need is tokenizer and annotated data? For the tokenizer, i understand it is needed and i can provide it. For the annotated data aren't you referring to the named entities annotation?

However, to my (not yet that strong) understanding, MITIE uses pre-trained models on a few languages (English, Spanish, German), so, in order to use Chinese (for the purposes of my project) shouldn't i provide Chinese word embedding and pre-trained models similar to the other languages?

**Comment by davisking** [comment]
Yes. That’s all correct.  You need to train a word embedding as well.

**Comment by alejandrokonto** [comment]
thanks for the prompt reply!
